# Generated by Django 5.0.3 on 2024-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/image/product/', verbose_name='Изображение'),
        ),
    ]
